baseURL = 'https://visviva.github.io/'
locale = 'en-us'
title = "visviva's blog"
theme = 'hugo-margin-tech'

[markup]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
[markup.highlight]
noClasses = false
lineNos = false

[params]
github = 'visviva'
name = 'Simon Lauser'
bio = 'I am a software engineer. I like to write about stuff that I do and find interesting.'
monoDarkIcon = true
math = true
