baseURL = 'https://visviva.github.io/'
locale = 'en-us'
title = 'My blog about stuff that I do and find interesting'
theme = 'hugo-margin-tech'

[markup]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
[markup.highlight]
noClasses = false
lineNos = false

[params]
github = 'visviva'
name = 'Simon Lauser'
bio = 'I am a software engineer. I like to write about stuff that I do and find interesting.'
monoDarkIcon = true
math = true

[menu]
[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 10
